### ISSUE TITLE
Obcasny problem s undefined country pri kontrole ICO/DIC

### ISSUE THREAD

**Issue by morvy** [vyskoczilova/kybernaut-ic-dic#27]
Obcas sa stane, ze pri odosielani objednavky nie je definovane billing_country. Predpokladam, ze su to pripady ked zakaznik iba odosle objednavku bez vyplnenych povinnych poli, no potom by nemala byt kontrola ostatnych poli ani spustena, kedze nema s cim porovnat.

Myslim, ze by stacilo pridat podmienku `if (!isset($_POST['billing_country'])) { return false; }`

```
ErrorException: Notice: Undefined index: billing_country
#13 /wp-content/plugins/woolab-ic-dic/includes/filters-actions.php(144): woolab_icdic_checkout_field_process
#12 /wp-includes/class-wp-hook.php(285): WP_Hook::apply_filters
#11 /wp-includes/class-wp-hook.php(311): WP_Hook::do_action
#10 /wp-includes/plugin.php(478): do_action
#9 /wp-content/plugins/woocommerce/includes/class-wc-checkout.php(1092): WC_Checkout::process_checkout
#8 /wp-content/plugins/woocommerce/includes/class-wc-form-handler.php(353): WC_Form_Handler::checkout_action
#7 /wp-includes/class-wp-hook.php(287): WP_Hook::apply_filters
#6 /wp-includes/class-wp-hook.php(311): WP_Hook::do_action
#5 /wp-includes/plugin.php(478): do_action
#4 /wp-settings.php(562): require_once
#3 /wp-config.php(108): require_once
#2 /wp-load.php(37): require_once
#1 /wp-blog-header.php(13): require
#0 /index.php(17): null
```

https://github.com/vyskoczilova/kybernaut-ic-dic/blob/c43c8771640554e9f005f9f141dee86f76fa3b31/includes/filters-actions.php#L144

**Comment by vyskoczilova** [comment]
@morvy Díky, přidáno, jdu to poslat na wordpress.org
