### ISSUE TITLE
1.7.0 Fatal error

### ISSUE THREAD

**Issue by vyskoczilova** [vyskoczilova/kybernaut-ic-dic#58]
Dobrý den,

dnes jsem provedl aktualizaci pluginů a woocommerce a při změně stavu objednávky mi vyskočil fatal error. Po deaktivaci Vašeho pluginu již vše funguje.
Posílám info o chybě.

WordPress version 6.2.2
Current theme: Storefront Child Theme (version 1.0.0)
Current plugin: Kybernaut IC DIC (version 1.7.0)
PHP version 7.4.33

```
Error Log Details
An error of type E_ERROR occurred on line 576 in the file /home/www/example.com/domains/example.com/sslsubdomains/eshop/wp-content/plugins/woolab-ic-dic/includes/filters-actions.php.
Error message: Uncaught Error: Call to undefined method WP_Post::update_meta_data() in /home/www/example.com/domains/example.com/sslsubdomains/eshop/wp-content/plugins/woolab-ic-dic/includes/filters-actions.php:576
Stack trace:
#0 /home/www/example.com/domains/example.com/sslsubdomains/eshop/wp-includes/class-wp-hook.php(308): woolab_icdic_process_shop_order(20933, Object(WP_Post))
#1 /home/www/example.com/domains/example.com/sslsubdomains/eshop/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters(NULL, Array)
#2 /home/www/example.com/domains/example.com/sslsubdomains/eshop/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#3 /home/www/example.com/domains/example.com/sslsubdomains/eshop/wp-content/plugins/woocommerce/includes/admin/class-wc-admin-meta-boxes.php(258): do_action('woocommerce_pro...', 20933, Object(WP_Post))
#4 /home/www/example.com/domains/example.com/sslsubdomains/eshop/wp-includes/class-wp-hook.php(310): WC_Admin_Meta_Boxes->save_meta_boxes(20933, Object(WP_Post))
#5 /home/www/example.com/domains/example.com/sslsubdomains/eshop/wp-includes/class-wp-hook.php(312): WC_Admin_Meta_Boxes->save_post(20933)
#6 /home/www/example.com/domains/example.com/sslsubdomains/eshop/wp-includes/plugin.php(484): WP_Hook->do_action(Array)
#7 /home/www/example.com/domains/example.com/sslsubdomains/eshop/wp-includes/post.php(3913): do_action('save_post', 20933, Object(WP_Post), true)
#8 /home/www/example.com/domains/example.com/sslsubdomains/eshop/wp-content/plugins/woocommerce/includes/data-stores/abstract-wc-order-data-store-cpt.php(122): wp_update_post(Object(WP_Post))
#9 /home/www/example.com/domains/example.com/sslsubdomains/eshop/wp-content/plugins/woocommerce/includes/data-stores/abstract-wc-order-data-store-cpt.php(75): WC_Order_Data_Store_CPT->update_post(Object(WP_Post))
#10 /home/www/example.com/domains/example.com/sslsubdomains/eshop/wp-content/plugins/woocommerce/packages/action-scheduler/classes/migration/ActionScheduler_DBStoreMigrator.php(202): WC_Order_Data_Store_CPT->create(Object(WC_Order))
#11 /home/www/example.com/domains/example.com/sslsubdomains/eshop/wp-content/plugins/woocommerce/packages/action-scheduler/classes/migration/ActionScheduler_DBStoreMigrator.php(178): ActionScheduler_DBStoreMigrator->import_to_custom_tables(Array, Object(WC_Order))
#12 /home/www/example.com/domains/example.com/sslsubdomains/eshop/wp-content/plugins/woocommerce/packages/action-scheduler/classes/migration/ActionScheduler_DBStoreMigrator.php(159): ActionScheduler_DBStoreMigrator->migrate_actions_to_custom_tables()
#13 /home/www/example.com/domains/example.com/sslsubdomains/eshop/wp-content/plugins/woocommerce/packages/action-scheduler/classes/migration/ActionScheduler_DBStoreMigrator.php(106): ActionScheduler_DBStoreMigrator->mark_migration_complete()
#14 /home/www/example.com/domains/example.com/sslsubdomains/eshop/wp-content/plugins/woocommerce/packages/action-scheduler/classes/migration/ActionScheduler_DBStoreMigrator.php(81): ActionScheduler_DBStoreMigrator->get_migration_complete_lock()
#15 /home/www/example.com/domains/example.com/sslsubdomains/eshop/wp-includes/class-wp-hook.php(332): ActionScheduler_DBStoreMigrator::register()
#16 /home/www/example.com/domains/example.com/sslsubdomains/eshop/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters(NULL, Array)
#17 /home/www/example.com/domains/example.com/sslsubdomains/eshop/wp-includes/plugin.php(544): WP_Hook->do_action(Array)
#18 /home/www/example.com/domains/example.com/sslsubdomains/eshop/wp-settings.php(579): do_action('init')
#19 /home/www/example.com/domains/example.com/sslsubdomains/eshop/wp-config.php(124): require_once('/home/www/exampl...')
#20 /home/www/example.com/domains/example.com/sslsubdomains/eshop/wp-load.php(37): require_once('/home/www/exampl...')
#21 /home/www/example.com/domains/example.com/sslsubdomains/eshop/wp-blog-header.php(13): require_once('/home/www/exampl...')
#22 /home/www/example.com/domains/example.com/index.php(17): require('/home/www/exampl...')
#23 {main}
thrown in /home/www/example.com/domains/example.com/sslsubdomains/eshop/wp-content/plugins/woolab-ic-dic/includes/filters-actions.php on line 576
```

// Reported via email.

**Comment by vyskoczilova** [comment]
Version 1.6.7 as stable on wordpress.org.

**Comment by morvy** [comment]
Pozrel som sa do kodu Woo a teda chyba na mojej strane, v tom hooku sa vzdy posiela WP_Post a nie WC_Order, neviem preco mi to IDE nezvyraznilo :/

https://github.com/woocommerce/woocommerce/blob/4ec75f7b261d4340551a98103ca208059f310087/plugins/woocommerce/includes/admin/class-wc-admin-meta-boxes.php#L258

**Comment by vyskoczilova** [comment]
Myslím, že kvůli tomu, že v commentu k funkci je, že je ten parametr WC_Order.
